config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :destroy
  resources :sessions, except: [:new, :destroy]
  resources :stories, except: :new
  resources :cities
  resources :places


 root to: "sites#index"
 get "/sign_in", to: "sessions#new"
 delete "/users", to: "users#destroy", as: "delete_user"
 delete "/sessions", to: "sessions#destroy", as: "sign_out"
 get "/city/:id/stories/new", to: "stories#new", as: "new_story"

end


#       Prefix Verb   URI Pattern                     Controller#Action
#        users GET    /users(.:format)                users#index
#              POST   /users(.:format)                users#create
#     new_user GET    /users/new(.:format)            users#new
#    edit_user GET    /users/:id/edit(.:format)       users#edit
#         user GET    /users/:id(.:format)            users#show
#              PATCH  /users/:id(.:format)            users#update
#              PUT    /users/:id(.:format)            users#update
#     sessions GET    /sessions(.:format)             sessions#index
#              POST   /sessions(.:format)             sessions#create
# edit_session GET    /sessions/:id/edit(.:format)    sessions#edit
#      session GET    /sessions/:id(.:format)         sessions#show
#              PATCH  /sessions/:id(.:format)         sessions#update
#              PUT    /sessions/:id(.:format)         sessions#update
#      stories GET    /stories(.:format)              stories#index
#              POST   /stories(.:format)              stories#create
#   edit_story GET    /stories/:id/edit(.:format)     stories#edit
#        story GET    /stories/:id(.:format)          stories#show
#              PATCH  /stories/:id(.:format)          stories#update
#              PUT    /stories/:id(.:format)          stories#update
#              DELETE /stories/:id(.:format)          stories#destroy
#       cities GET    /cities(.:format)               cities#index
#              POST   /cities(.:format)               cities#create
#     new_city GET    /cities/new(.:format)           cities#new
#    edit_city GET    /cities/:id/edit(.:format)      cities#edit
#         city GET    /cities/:id(.:format)           cities#show
#              PATCH  /cities/:id(.:format)           cities#update
#              PUT    /cities/:id(.:format)           cities#update
#              DELETE /cities/:id(.:format)           cities#destroy
#       places GET    /places(.:format)               places#index
#              POST   /places(.:format)               places#create
#    new_place GET    /places/new(.:format)           places#new
#   edit_place GET    /places/:id/edit(.:format)      places#edit
#        place GET    /places/:id(.:format)           places#show
#              PATCH  /places/:id(.:format)           places#update
#              PUT    /places/:id(.:format)           places#update
#              DELETE /places/:id(.:format)           places#destroy
#         root GET    /                               sites#index
#      sign_in GET    /sign_in(.:format)              sessions#new
#  delete_user DELETE /users(.:format)                users#destroy
#     sign_out DELETE /sessions(.:format)             sessions#destroy
#    new_story GET    /city/:id/stories/new(.:format) stories#new

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :stories

  validates :email, uniqueness: true, confirmation: true
  validates :password, length: { minimum: 6}

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in?, only: [:edit, :destroy]
  before_action :set_user, only: [:index, :update, :destroy]

  def index
    set_user
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user) 
      redirect_to user_path(@user)
    else
      flash[:notice] = @user.errors.full_messages.to_sentence
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.assign_attributes(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      flash[:notice] = "Email already in use"
      redirect_to edit_user_path
    end
  end

  def destroy
    @user.destroy()
    sign_out
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :city, :email, :password, :pasword_confirmation)
  end

  def set_user
    @user = current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
    <%= form_for user, html: { class: "form-group"} do |f| %>

      <% if flash[:notice] %>
        <div class="alert alert-danger col-md-12" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <div class="form-group col-md-6 " >
          <label>Username</label>
          <%= f.text_field :username, placeholder: "Username", class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <label>Home City</label>
        <%= f.text_field :city, placeholder: "San Francisco", class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <label>First Name</label>
        <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <label>Last Name</label>
        <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <label>Email</label>
        <%= f.email_field :email, placeholder: "Email", class: "form-control " %>
      </div>

      <div class="form-group col-md-6">
        <label>Confirm Email</label>
        <%= f.email_field :email, placeholder: "Confirm Email", class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <label>Password</label>
        <%= f.password_field :password, placeholder: "password", class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <label>Confirm Password</label>
        <%= f.password_field :password_confirmation, placeholder: "confirm password", class: "form-control" %>
      </div>

      <div class="col-md-6">
        <%= f.submit class: "btn btn-primary" %>
      </div>

    <% end %>
  </form>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1 class="col-md-12">Edit Profile</h1>
<%= render partial: "users/form", locals: {user: @user} %>

    <div class="form-group">
      <%= link_to "Cancel", "javascript:history.go(-1);", class: "col-sm-1" %>
      <%= link_to 'Delete', user_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "col-sm-1 pull-right" %>
    </div>

app/views/users/new.html.erb
<h1 class="col-md-12">Sign Up</h1>

<%= render partial: "users/form", locals: {user: @user} %>

app/views/users/show.html.erb
<div class="col-md-12">
  <h1><%= @user.username %></h1>
</div>

<div class="col-md-3">

  <%= image_tag gravatar_url(@user.email, 200), alt: "" %>
  <p><%= @user.first_name + " " + @user.last_name %></p>
  <p><%= @user.city %></p>
  <p>Joined <%= @user.created_at.strftime("%B %Y") %></p>

  <% if current_user == @user %>
    <%= link_to "Edit Profile", edit_user_path(@user) %>
  <% end %>
</div>

<div class="col-md-7">
  <h4>Stories</h4>
  <% @user.stories.each do |s| %>
    <h3><%= link_to s.title, story_path(s) %></h3>
    <p><%= h truncate(s.body, :length =>70) %></p>
    <% if current_user == @user %>
      <%= link_to 'Edit', edit_story_path(s) %>
    <% end %>
  <% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>