config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :destroy
  resources :sessions, except: [:new, :destroy]
  resources :stories, except: :new
  resources :cities
  resources :places


 root to: "sites#index"
 get "/sign_in", to: "sessions#new"
 delete "/users", to: "users#destroy", as: "delete_user"
 delete "/sessions", to: "sessions#destroy", as: "sign_out"
 get "/city/:id/stories/new", to: "stories#new", as: "new_story"

end


#       Prefix Verb   URI Pattern                     Controller#Action
#        users GET    /users(.:format)                users#index
#              POST   /users(.:format)                users#create
#     new_user GET    /users/new(.:format)            users#new
#    edit_user GET    /users/:id/edit(.:format)       users#edit
#         user GET    /users/:id(.:format)            users#show
#              PATCH  /users/:id(.:format)            users#update
#              PUT    /users/:id(.:format)            users#update
#     sessions GET    /sessions(.:format)             sessions#index
#              POST   /sessions(.:format)             sessions#create
# edit_session GET    /sessions/:id/edit(.:format)    sessions#edit
#      session GET    /sessions/:id(.:format)         sessions#show
#              PATCH  /sessions/:id(.:format)         sessions#update
#              PUT    /sessions/:id(.:format)         sessions#update
#      stories GET    /stories(.:format)              stories#index
#              POST   /stories(.:format)              stories#create
#   edit_story GET    /stories/:id/edit(.:format)     stories#edit
#        story GET    /stories/:id(.:format)          stories#show
#              PATCH  /stories/:id(.:format)          stories#update
#              PUT    /stories/:id(.:format)          stories#update
#              DELETE /stories/:id(.:format)          stories#destroy
#       cities GET    /cities(.:format)               cities#index
#              POST   /cities(.:format)               cities#create
#     new_city GET    /cities/new(.:format)           cities#new
#    edit_city GET    /cities/:id/edit(.:format)      cities#edit
#         city GET    /cities/:id(.:format)           cities#show
#              PATCH  /cities/:id(.:format)           cities#update
#              PUT    /cities/:id(.:format)           cities#update
#              DELETE /cities/:id(.:format)           cities#destroy
#       places GET    /places(.:format)               places#index
#              POST   /places(.:format)               places#create
#    new_place GET    /places/new(.:format)           places#new
#   edit_place GET    /places/:id/edit(.:format)      places#edit
#        place GET    /places/:id(.:format)           places#show
#              PATCH  /places/:id(.:format)           places#update
#              PUT    /places/:id(.:format)           places#update
#              DELETE /places/:id(.:format)           places#destroy
#         root GET    /                               sites#index
#      sign_in GET    /sign_in(.:format)              sessions#new
#  delete_user DELETE /users(.:format)                users#destroy
#     sign_out DELETE /sessions(.:format)             sessions#destroy
#    new_story GET    /city/:id/stories/new(.:format) stories#new

app/models/city.rb
class City < ActiveRecord::Base
	has_many :stories

	validates :name, presence: true, uniqueness: true
	validates :continent, presence: true
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

	before_action :set_user

	def index
		@cities = City.all
		@continents = ["North America", "South America", "Europe", "Asia", "Australia", "Africa"]
		render :index
	end

	def new
	end

	def create
	end

	def show
		set_city
		render :show
	end

	def edit
	end

	def update
	end


	def destroy
	end

	private

	def set_user
	  @user = current_user
	end

	def set_city
	  @city = City.find(params[:id])
	end


end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<h1 class="col-md-12">CITIES</h1>

<ul class="col-md-12">
<% @cities.each do |c| %>
	<h3 ><%= link_to c.name, city_path(c) %></h3>
<% end %>
</ul>

app/views/cities/show.html.erb
<div id="map-container">
    <div id="map-canvas"></div>
    <input id="pac-input" class="controls" type="text" placeholder="Search for an address">
</div>

<div class="content-container">
<div class="container">
    <div id="city_name" class="col-sm-10", id: "city"><h2><%= @city.name %></h2></div>
    <%= button_to "New Post", new_story_path, method: "get", class: "btn btn-default col-xs-2", id: "new-post-bttn" %>

          <div id="stories_list">
           <% @city.stories.order("created_at DESC").each do |s| %>
               <div class="row post">
                <div>
                  <% if s.user_id != nil %>
                    <a id="user-img" class="pull-left">
                        <%= image_tag gravatar_url(User.find(s.user_id).email, 100), alt: "", class: "user_img_city_posts" %>
                    </a>
                  <% end %>
                </div>
                    <div class="title">
                        <h2><%= link_to s.title, story_path(s) %></h2>
                    </div>
                    <div class="body">
                        <h4><%=h truncate(s.body, :length =>70) %></h4>
                    </div>
                </div>
                <hr>
           <% end %>
          </div>
    </div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhvWvwmJ8clstnuG4S4I2JeCb6bvDF824&libraries=places&callback=vagabond_map.ready"></script>
<%= javascript_include_tag "cities", "data-turbolinks-track" => true %>